### ISSUE TITLE
Failed installation of mautic 3.x. through composer

### ISSUE THREAD

**Issue by Rol-a** [nickveenhof/mautic-project#1]
@Nick, thank you very much again for this. For any one else who sees this it is not really an issue rather, it is me asking for a help. Basically, I would like to be able to install a production instance of the latest stable mautic using composer. I did try few things and here are my results so far.
Env: Ubuntu 18.04 LTS, 4 GB RAM, 2 vCPUs, 80 GB SSD

For a first attempt I used this project here the nickveenhof/mautic-project:3.x-dev, tried composer install and failed

        mmap() failed: [12] Cannot allocate memory
        PHP Fatal error:  Out of memory

The lines above were the error. I tried to solve it by alter the Memory_limit without success.
Again I am not really sure what I am doing but my assumption was that I had some file permission issue somewhere.
https://gist.github.com/Rol-a/d0b893147a63967828bea718ebeb0e71

I then decided to try something else. Again still used the same environment above. This time however, I simply decided to pull the 3.0.2 source folder from mautic repository, extracted it and again composer install it. First half of the installation was complete, but the second half which is the browser installation didn't work. I have to mention that even the first half completed has some security flaws in it (giving a 777 permission to the mautic web folder for example. I am still trying few things here. Thanks again@nick. Thank you very much.
https://gist.github.com/Rol-a/2e01294086c348c5648758412339bd42

Some log records as well for the second attempt as well as the browser screenshot.
https://gist.github.com/Rol-a/ac2dadb50c70dec7abb6d31a2d643301
https://user-images.githubusercontent.com/68291091/89723189-055b3380-d9c1-11ea-9062-f03917331d0f.png

**Comment by pjoulot** [comment]
I could go through the install process without any issue due to memory.
composer is using lots of RAM, did you have any other applications open? I would suggest to try again when everything is closed except your terminal, or to upgrade your computer. Mine is sometimes freezing with 8GB of RAM when running composer and not closing my browser.

**Comment by nickveenhof** [comment]
This looks indeed more a local issue and not per se an issue with the code. I would suggest the slack channels if you need more guided help. Good luck! :-)
