### ISSUE TITLE
Cannot apply patch Make sure the lifetime interval is an integer (https://patch-diff.githubusercontent.com/raw/mautic/mautic/pull/8665.patch)!

### ISSUE THREAD

**Issue by pjoulot** [nickveenhof/mautic-project#2]
When installing mautic 3, the composer install is crashing because one of the patch is outdated and mautic seems to already have fixed that issue.
`
Cannot apply patch Make sure the lifetime interval is an integer (https://patch-diff.githubusercontent.com/raw/mautic/mautic/pull/8665.patch)!`

If you look at mautic repository, the code is already changed:
https://github.com/mautic/mautic/blob/3.x/app/config/security.php

**Comment by pjoulot** [comment]
See pull request: #3

**Comment by nickveenhof** [comment]
All fixed
