### ISSUE TITLE
Config is removed when running composer update

### ISSUE THREAD

**Issue by pjoulot** [nickveenhof/mautic-project#7]
The config is ignored which is normal because it can change depending on the environment. But it is removed when running composer install/update!
So you have to reinstall the whole website once composer is done because you will loose the configuration to connect to the database.
The config folder should not be overriden by a composer install/update.

**Comment by nickveenhof** [comment]
We solve this on our end by actually moving a file to the local.php file after a deploy. But I agree, this should ideally be fixed. This is normally solved with scaffolding and needs a bigger change to Mautic core for this to be resolved. Please follow https://forum.mautic.org/t/as-a-developer-i-want-to-be-able-to-apply-patches-and-upgrade-mautic-core-within-the-existing-composer-json/13750 for progress
