### ISSUE TITLE
Test for a new Mautic site - unable to properly create codebase

### ISSUE THREAD

**Issue by ultimike** [nickveenhof/mautic-project#8]
I finally got around to trying your Composer template today. A couple of things I found…

1. I had to do a `composer create-project … --no-install` and then change the mautic/core version to ^3.2 and then run `composer install` - 3.x-dev wasn't working for me.
2. After that, Mautic was still installed in the /vendor/ directory. I did a `composer update mautic/core --with-dependencies` and that seemed to get it in the right place.
3. Then I deleted the /vendor/ directory and did another `composer install` because I noticed that mautic/core/ was also in the /vendor/ directory - that didn’t seem correct. After the `composer install` it was still in both places.
4. Trying to load Mautic at this point leads to a fatal error: Fatal error: require(): Failed opening required '/var/www/html/public/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/public/app/autoload.php on line 11

I tried this with DDEV as my local environment. The only other thing I did (manually) was create a .env file from .env.example

-mike

**Comment by nickveenhof** [comment]
Should be fixed by now :)
